name: Cypress Tests

on:
  push:
    paths: 
      - 'sapperapp/**'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Run
        uses: cypress-io/github-action@v1
        with:
          working-directory: sapperapp
          spec: cypress/integration/spec.js
          build: npm run build
          start: npm run start
          wait-on: 'http://localhost:3000'
